# -*- coding: utf-8 -*-
"""Verificador de senhas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSqwz_Soohckr6MxrpzU8M49av1V0Vij
"""

import time
caracteres = ['@','!','?','%','$','&','*','(',')','+','/','#']

while True:
  maiusculo = False
  especiais = False
  numeros = False

  senha = input('Digite sua senha: ')
  print('Analisando senha...')
  time.sleep(4)
  if len(senha) < 10:
    print(f'Senha muito curta, mínimo 12, ❌ (Caracteres inseirdos {len(senha)})')
  else:
    print('Quantidade de caracteres adequada✔️')

  for x in senha:
    if x.upper() in senha[0:11]:
        maiusculo = True
        print('Letra(s) maiúscula✔️')
        break
  else:
    print('Precisa ter uma letra(s) maiúscula ❌')

  for x in caracteres:
    if x in senha:
      especiais = True
      print('Caracter especial encontrado ✔️')
      break
  else:
      print('Use caracter especial ❌')

  for c in senha:
    if c.isdigit():
      numeros = True
      print('Possui número(s) ✔️')
      break
  else:
      print('Precisa ter números ❌')
  # ----------------# Checagem de nível de proteção----------------
  print('Analisando Nível de proteção...')
  time.sleep(1)
  if maiusculo and especiais and numeros and len(senha) >= 10:
          print('Nível de segurança: Alto 🟩')
          break
  elif not maiusculo and not especiais and not numeros:
        print('Nível de segurança: Baixo 🟥')
  else:
      print('Nível de segurança: Médio 🟨')
  print('Tente novamente.\n')

